spring:
  application:
    name: mixi-user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:ENC(wuxmSwTVsNPnvznsPQ9Da6aAZ9HVaSUjscJmUqSBszl5PF0J/6W6qn5bviPb3cEtq9gsmRQ9OXv7SkB3m/tNZEaqXvwGJN7Iu0pw01PILPurQyi6J8nYj3J6E4vQSlaZ)}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:timeMachineLabMysql1314}
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:124.71.72.118}
      username: ${NACOS_SERVER_USER:nacos}
      password: ${NACOS_SERVER_PASSWORD:timeMachineLabNacos1314}
      discovery:
        namespace: b21e6a4b-33d1-44c3-9b24-8a682c897292
        ip: ${SERVER_ADDR:127.0.0.1}
  redis:
    host: ${REDIS_HOST:ENC(DoATKT3H6aEIGPC0FL69KkjLvrJKnw9q/oQ9kPs5Vt4=)}
    port: 6379
    database: 10
    password: ${REDIS_PASSWORD:ENC(3SF9cUbQq5wcQbZF42lbEm6RH9zB6Y5sGZIoUymT+exjpy1oFbGb0A==)}
email:
  myEmailAccount: ${EMAIL_ACCOUNT:ENC(yZ7mbew/WOwpCHb1RlrgLBLQhNWKScodQVXkggwnSYxrJn9a8au+tA==)}
  myEmailPassword: ${EMAIL_PASSWORD:ENC(qNez9SZIeXRJNOAyzPkvDRYdJ3OnsMQvhWugcefAtrZXIZ9A7RgkOA==)}
env:
  ip: 127.0.0.1
  port: 9010
sa-token:
  token-name: token
  timeout: 259200
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: true